#X-Generator: crowdin.com
# authentication error messages
authentication.err.validation.authenticator.notfound=No s'ha pogut autenticar, autenticador amb nom, {0}, no trobat
authentication.err.validation.authenticator.notactive=El autenticador no est\u00e0 actiu

authentication.err.authentication=No s'ha pogut autenticar, nom d'usuari o la contrasenya est\u00e0 malament. Nom d'usuari\: {0} ra\u00f3 {1}
authentication.err.connection=No ha pogut connectar a {0}. Ra\u00f3 {1}
authentication.err.communication=No ha pogut comunicar-se amb {0}. Ra\u00f3 {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=Error en connectar, el host de ldap {0} \u00e9s desconegut
authentication.err.connection.ldap.user.notfound=Usuari de LDAP {0} no trobat
authentication.err.connection.ldap.manager.notfound=No s'ha trobat l'usuari administrador LDAP {0}
authentication.err.connection.ldap.search=No s'ha pogut buscar a LDAP. Ra\u00f3 {0}

# PASSTHRU
authentication.err.connection.passthru.server=No s'ha pogut obrir la sessi\u00f3 al servidor passthru
authentication.err.passthru.token.unsupported=Tipus de token d'autenticaci\u00f3 no compatible
authentication.err.passthru.guest.notenabled=Inicis de sessi\u00f3 com invitat deshabilitats
authentication.err.passthru.user.disabled=Compte inhabilitat
authentication.err.passthru.user.notfound=L'usuari de passthru {0} no trobat

# Authentication Diagnostic Steps
authentication.step.ldap.validation=Validaci\u00f3 de la sol\u00b7licitud
authentication.step.ldap.connecting=Connectant al servidor LDAP {0} 
authentication.step.ldap.connected=Connectat al servidor LDAP {0} amb principal\: {1}
authentication.step.ldap.lookup=Cerca l'usuari de prova amb Id. d'usuari\: {0} amb la consulta\: {1}
authentication.step.ldap.lookedup=Buscat el Id. d'usuari de prova\:{0}, s'ha trobat el nom distintiu (DN)\:{1}
authentication.step.ldap.format.user=Especificat Format de nom d'usuari, userNameFormat\:{2} Format de l'id. del usuari userId\:{0} per crear nom distintiu (DN)\:{1}
authentication.step.ldap.authentication=Autenticar userId\: {0}


# Sync Summary message 
synchronization.summary.status={0} usuari(s) i {1} grup(s) processats


# Error messages
authentication.ldap.validation.authenticator.notfound=Autenticaci\u00f3 no trobada

# Synchronization Diagnostic Steps
synchronization.step.users=Trobats {0} usuaris
synchronization.step.groups=Trobats {0} grups
synchronization.step.users.lastsynced=\u00daltims {0} usuaris sincronitzats amb \u00e8xit
synchronization.step.groups.lastsynced=Darrers {0} grups sincronitzats amb \u00e8xit

synchronization.err.ldap.search=Error durant la cerca de LDAP. Ra\u00f3\: {0}
synchronization.err.ldap.get.user.id.missing=Al usuari li falta l'atribut d'identificador d'usuari DN \= {0}, attributeName \= {1})
synchronization.err.ldap.get.group.id.missing=Al grup li falta l'atribut identificador de grup DN \= {0}, attributeName \= {1})

synchronization.err.ldap.search.base.invalid=Base de cerca no v\u00e0lida {0} ra\u00f3\: {1}

synchronization.err.ldap.group.member.missing.exception="No s'ha pogut resoldre el membre del grup {0} amb el nom distintiu\: {1}, ra\u00f3 {2});
synchronization.err.ldap.group.member.missing="No s'ha pogut resoldre el membre del grup {0} amb el nom distintiu\: {1});








