#X-Generator: crowdin.com
# authentication error messages
authentication.err.validation.authenticator.notfound=\uc778\uc99d\uc5d0 \uc2e4\ud328\ud588\uc2b5\ub2c8\ub2e4. {0} \uc774\ub984\uc744 \uac00\uc9c4 \uc778\uc99d\uc790\uac00 \uc5c6\uc2b5\ub2c8\ub2e4
authentication.err.validation.authenticator.notactive=\uc778\uc99d\uc790\ub294 \ud65c\uc131 \uc0c1\ud0dc\uac00 \uc544\ub2d9\ub2c8\ub2e4

authentication.err.authentication=\uc778\uc99d\uc5d0 \uc2e4\ud328\ud558\uc600\uc2b5\ub2c8\ub2e4. \uc0ac\uc6a9\uc790 \uc774\ub984 \ub610\ub294 \uc554\ud638\uac00 \uc798\ubabb\ub418\uc5c8\uc2b5\ub2c8\ub2e4. \uc0ac\uc6a9\uc790 \uc774\ub984\:{0}, \uc6d0\uc778 {1}
authentication.err.connection={0}\uc73c\ub85c \uc5f0\uacb0\uc5d0 \uc2e4\ud328\ud588\uc2b5\ub2c8\ub2e4. \uc6d0\uc778 {1}
authentication.err.communication={0}\uc640\uc758 \ud1b5\uc2e0\uc5d0 \uc2e4\ud328\ud588\uc2b5\ub2c8\ub2e4. \uc6d0\uc778 {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=\uc5f0\uacb0\uc5d0 \uc2e4\ud328\ud588\uc2b5\ub2c8\ub2e4. {0} LDAP \ud638\uc2a4\ud2b8\ub97c \uc54c \uc218 \uc5c6\uc2b5\ub2c8\ub2e4
authentication.err.connection.ldap.user.notfound={0} LDAP \uc0ac\uc6a9\uc790\uac00 \uc5c6\uc2b5\ub2c8\ub2e4
authentication.err.connection.ldap.manager.notfound={0} LDAP \uad00\ub9ac \uc0ac\uc6a9\uc790\uac00 \uc5c6\uc2b5\ub2c8\ub2e4
authentication.err.connection.ldap.search=LDAP\ub97c \uac80\uc0c9\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4. \uc6d0\uc778 {0}

# PASSTHRU
authentication.err.connection.passthru.server=\ud328\uc2a4\uc2a4\ub8e8 \uc11c\ubc84\uc5d0 \uc138\uc158\uc744 \uc5ec\ub294\ub370 \uc2e4\ud328\ud588\uc2b5\ub2c8\ub2e4
authentication.err.passthru.token.unsupported=\uc9c0\uc6d0\ud558\uc9c0 \uc54a\ub294 \uc778\uc99d \ud1a0\uadfc \ud615\uc2dd\uc785\ub2c8\ub2e4
authentication.err.passthru.guest.notenabled=\uc190\ub2d8 \ub85c\uadf8\uc628\uc744 \uc0ac\uc6a9\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4
authentication.err.passthru.user.disabled=\uacc4\uc815\uc744 \uc0ac\uc6a9\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4
authentication.err.passthru.user.notfound={0} \ud328\uc2a4\uc2a4\ub8e8 \uc0ac\uc6a9\uc790\uac00 \uc5c6\uc2b5\ub2c8\ub2e4

# Authentication Diagnostic Steps
authentication.step.ldap.validation=\uc694\uccad \uac80\uc0ac
authentication.step.ldap.connecting={0} LDAP \uc11c\ubc84\uc5d0 \uc5f0\uacb0\uc911 
authentication.step.ldap.connected=\ubcf4\uc548 \uc8fc\uccb4\ub97c \ud1b5\ud574 {0} LDAP \uc11c\ubc84\uc5d0 \uc5f0\uacb0\ud588\uc2b5\ub2c8\ub2e4\: {1}
authentication.step.ldap.lookup={1} \uc694\uccad\uc73c\ub85c {0} \uc0ac\uc6a9\uc790 ID\ub97c \uac00\uc9c4 \uc2dc\ud5d8 \uc0ac\uc6a9\uc790 \ucc3e\ub294 \uc911
authentication.step.ldap.lookedup=Looked up Test User userId\:{0}, found distinguished name (DN)\:{1}
authentication.step.ldap.format.user=User Name Format specified, userNameFormat\:{2} Format user userId\:{0} to make Distinguished name (DN)\:{1}
authentication.step.ldap.authentication=Authenticate userId\:{0}


# Sync Summary message 
synchronization.summary.status={0} user(s) and {1} group(s) processed


# Error messages
authentication.ldap.validation.authenticator.notfound=Authenticator not found

# Synchronization Diagnostic Steps
synchronization.step.users=\uc0ac\uc6a9\uc790 {0}\uba85\uc744 \ucc3e\uc558\uc2b5\ub2c8\ub2e4
synchronization.step.groups=\uadf8\ub8f9 {0}\uac1c\ub97c \ucc3e\uc558\uc2b5\ub2c8\ub2e4
synchronization.step.users.lastsynced=Users last successfully synced {0}
synchronization.step.groups.lastsynced=Groups last successfully synced {0}

synchronization.err.ldap.search=LDAP \uac80\uc0c9\uc744 \uc218\ud589\ud558\ub294 \ub3d9\uc548 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4. \uc6d0\uc778\: {0}
synchronization.err.ldap.get.user.id.missing=User missing user id attribute DN \= {0}, attributeName \= {1})
synchronization.err.ldap.get.group.id.missing=Group missing group id attribute DN \= {0}, attributeName \= {1})

synchronization.err.ldap.search.base.invalid=Invalid search base {0} reason\: {1}

synchronization.err.ldap.group.member.missing.exception="Failed to resolve member of group {0} with distinguished name\: {1}, reason {2});
synchronization.err.ldap.group.member.missing="Failed to resolve member of group {0} with distinguished name\: {1});








