#X-Generator: crowdin.com
# authentication error messages
authentication.err.validation.authenticator.notfound=Autorizacijos klaida, vardas "{0}" nerastas
authentication.err.validation.authenticator.notactive=Autorizacija neaktyvi

authentication.err.authentication=Autorizacijos klaida, blogas vardas arba slapta\u017eodis. Vartotojo vardas\: {0} prie\u017eastis {1}
authentication.err.connection=Nepavyko prisijungti prie {0}. Prie\u017eastis {1}
authentication.err.communication=Nepavyko susisiekti su {0}. Prie\u017eastis {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=Nepavyko prisijungti, LDAP domainas {0} ne\u017einomas
authentication.err.connection.ldap.user.notfound=LDAP vartotojas {0} nerastas
authentication.err.connection.ldap.manager.notfound=LDAP Manager User {0} not found
authentication.err.connection.ldap.search=Ne\u012fmanoma surasti LDAP. Prie\u017eastis {0}

# PASSTHRU
authentication.err.connection.passthru.server=Nepavyko atidaryti slapta\u017eod\u017ei\u0173 patikros serverio seans\u0105
authentication.err.passthru.token.unsupported=Nepalaikomas autentifikavimo u\u017eklausos tipas
authentication.err.passthru.guest.notenabled=Sve\u010di\u0173 \u012f\u0117jimams i\u0161jungtas
authentication.err.passthru.user.disabled=Paskyra i\u0161jungta
authentication.err.passthru.user.notfound="Passthru" vartotojas {0} nerastas

# Authentication Diagnostic Steps
authentication.step.ldap.validation=Patvirtinimo u\u017eklausa
authentication.step.ldap.connecting=Jungiamasi prie LDAP serverio {0} 
authentication.step.ldap.connected=Prisijungta prie LDAP serverio {0} naudojant {1}
authentication.step.ldap.lookup=Lookup Test User userId\:{0} with query\: {1}
authentication.step.ldap.lookedup=Looked up Test User userId\:{0}, found distinguished name (DN)\:{1}
authentication.step.ldap.format.user=User Name Format specified, userNameFormat\:{2} Format user userId\:{0} to make Distinguished name (DN)\:{1}
authentication.step.ldap.authentication=Authenticate userId\:{0}


# Sync Summary message 
synchronization.summary.status={0} user(s) and {1} group(s) processed


# Error messages
authentication.ldap.validation.authenticator.notfound=Authenticator not found

# Synchronization Diagnostic Steps
synchronization.step.users=Rasta {0} vartotoj\u0173
synchronization.step.groups=Rasta {0} grupi\u0173
synchronization.step.users.lastsynced=Users last successfully synced {0}
synchronization.step.groups.lastsynced=Groups last successfully synced {0}

synchronization.err.ldap.search=Error during LDAP Search. Reason\:{0}
synchronization.err.ldap.get.user.id.missing=User missing user id attribute DN \= {0}, attributeName \= {1})
synchronization.err.ldap.get.group.id.missing=Group missing group id attribute DN \= {0}, attributeName \= {1})

synchronization.err.ldap.search.base.invalid=Invalid search base {0} reason\: {1}

synchronization.err.ldap.group.member.missing.exception="Failed to resolve member of group {0} with distinguished name\: {1}, reason {2});
synchronization.err.ldap.group.member.missing="Failed to resolve member of group {0} with distinguished name\: {1});








