#X-Generator: crowdin.com
# authentication error messages
authentication.err.validation.authenticator.notfound=Kimlik do\u011frulamas\u0131 yap\u0131lamad\u0131,{0} isimde Kullan\u0131c\u0131 bulunmamaktad\u0131r
authentication.err.validation.authenticator.notactive=Kimlik do\u011frulama sistemi aktif de\u011fil

authentication.err.authentication=Kimlik do\u011frulama hatas\u0131, kullan\u0131c\u0131 ad\u0131 ve/veya \u015fifre hatal\u0131. Kullan\u0131c\u0131 ad\u0131\:{0} Hata nedeni {1}
authentication.err.connection={0} \u00f6\u011fesine ba\u011flant\u0131 ba\u015far\u0131s\u0131z oldu. Hata nedeni {1}
authentication.err.communication={0} ile ileti\u015fim kurulamad\u0131. Neden {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=Ba\u011flant\u0131 ba\u015far\u0131s\u0131z oldu. {0} ldap hostu bulunamad\u0131
authentication.err.connection.ldap.user.notfound={0} LDAP kullan\u0131c\u0131s\u0131  bulunamad\u0131
authentication.err.connection.ldap.manager.notfound={0} LDAP Y\u00f6neticisi kullan\u0131c\u0131s\u0131  bulunamad\u0131
authentication.err.connection.ldap.search=LDAP \u00fczerinden arama yap\u0131lam\u0131yor. Hata nedeni {0}

# PASSTHRU
authentication.err.connection.passthru.server=Ge\u00e7i\u015f sunucusuna oturum a\u00e7ma ba\u015far\u0131s\u0131z oldu
authentication.err.passthru.token.unsupported=Desteklenmeyen kimlik do\u011frulama belirteci t\u00fcr\u00fc
authentication.err.passthru.guest.notenabled=Konuk oturumlar\u0131 devre d\u0131\u015f\u0131
authentication.err.passthru.user.disabled=Hesap devre d\u0131\u015f\u0131
authentication.err.passthru.user.notfound=Ge\u00e7i\u015f kullan\u0131c\u0131s\u0131 {0} bulunamad\u0131

# Authentication Diagnostic Steps
authentication.step.ldap.validation=Do\u011frulama iste\u011fi
authentication.step.ldap.connecting={0} LDAP sunucusuna ba\u011flan\u0131l\u0131yor
authentication.step.ldap.connected={0} LDAP sunucuna {1} ile ba\u011fl\u0131
authentication.step.ldap.lookup=Lookup Test User userId\:{0} with query\: {1}
authentication.step.ldap.lookedup=Looked up Test User userId\:{0}, found distinguished name (DN)\:{1}
authentication.step.ldap.format.user=User Name Format specified, userNameFormat\:{2} Format user userId\:{0} to make Distinguished name (DN)\:{1}
authentication.step.ldap.authentication=Authenticate userId\:{0}


# Sync Summary message 
synchronization.summary.status={0} user(s) and {1} group(s) processed


# Error messages
authentication.ldap.validation.authenticator.notfound=Authenticator not found

# Synchronization Diagnostic Steps
synchronization.step.users={0} kullan\u0131c\u0131 bulundu
synchronization.step.groups={0} Grup bulundu
synchronization.step.users.lastsynced=Users last successfully synced {0}
synchronization.step.groups.lastsynced=Groups last successfully synced {0}

synchronization.err.ldap.search=LDAP aramas\u0131 s\u0131ras\u0131nda hata olu\u015ftu. Sebep\: {0}
synchronization.err.ldap.get.user.id.missing=User missing user id attribute DN \= {0}, attributeName \= {1})
synchronization.err.ldap.get.group.id.missing=Group missing group id attribute DN \= {0}, attributeName \= {1})

synchronization.err.ldap.search.base.invalid=Ge\u00e7ersiz arama alan\u0131 {0} sebep\: {1}

synchronization.err.ldap.group.member.missing.exception="Failed to resolve member of group {0} with distinguished name\: {1}, reason {2});
synchronization.err.ldap.group.member.missing="Failed to resolve member of group {0} with distinguished name\: {1});








