#X-Generator: crowdin.com
# Content-related messages

content.content_missing=Uzol obsahu ch\u00fdba\: \n uzol\: {0} \n \u010ditate\u013e\: {1}\n obr\u00e1\u0165te sa na V\u00e1\u0161ho spr\u00e1vcu syst\u00e9mu.
content.runtime_exec.property_moved=The property ''errorCodes'' has moved down onto the RuntimeExec class

index.recovery.out_of_date=Indexy nie s\u00fa synchronizovan\u00e9 s datab\u00e1zou.
index.tracking.starting=Index obnovy za\u010dal.
index.tracking.complete=Index obnovy dokon\u010den\u00fd.
index.tracking.progress=\ Spracovanie transakci\u00ed okolo {0}.
index.recovery.starting=Index obnovy za\u010dal\: {0} transakcie.
index.recovery.complete=Index obnovy dokon\u010den\u00fd.
index.recovery.progress=\ {0} % kompletn\u00fd.
index.recovery.terminated=Obnova indexu ukon\u010den\u00e1.

node.archive.msg.busy=Hromadn\u00e1 \u010distka, alebo pr\u00e1ve prebieha oper\u00e1cia obnovenia

content.http_reader.err.no_connection=Ned\u00e1 sa pripoji\u0165 k vzdialen\u00e9mu serveru Alfresco cez HTTP\: {0}
content.http_reader.err.no_authentication=HTTP \u010ditate\u013e sa nepodarilo overi\u0165 na vzdialenom serveri\: {0}   
content.http_reader.err.check_cluster=Uistite sa, \u017ee "replicateUpdates" a "replicateUpdatesViaCopy" s\u00fa povolen\u00e9 pre vyrovn\u00e1vaciu pam\u00e4\u0165 "org.alfresco.cache.ticketsCache". Overte, \u017ee v\u0161eobecn\u00e1 konfigur\u00e1cia klastra je spr\u00e1vna a pracuje.
content.http_reader.err.unrecognized=Nezn\u00e1ma chyba pri pokuse o prevzatie obsahu zo vzdialen\u00e9ho servera\: \n  Server\: {0} \n  Obsahu\: {1}\n  Odpove\u010f HTTP\: {2}

metadata.extraction.err.type_conversion=Metad\u00e1ta extrakcie zlyhali, preto\u017ee z\u00edskan\u00e9 hodnoty sa nepodarilo konvertova\u0165 na po\u017eadovan\u00fd typ.\: \n  Extractor\: {0} \n  N\u00e1zov vlastnosti cie\u013ea QName\: {1} \n  Po\u017eadovan\u00fd typ\: {2}\n  Extrahovan\u00e1 hodnota \: {3}

transform.err.format_or_password=Nepodarilo sa konvertova\u0165 obsah, mo\u017eno kv\u00f4li nespr\u00e1vne form\u00e1tovan\u00e9mu alebo heslom chr\u00e1nen\u00e9mu s\u00faboru.

content.routing.err.invalid_default_store="DefaultStoreName", "{0}" sa nevz\u0165ahuje na \u00falo\u017eisko v "storesByName" ({1}).
