#X-Generator: crowdin.com
# Content-related messages

content.content_missing=Nodens indhold mangler\: \nnode\: {0} \nl\u00e6ser\: {1} \nKontakt venligst din systemadministrator.
content.runtime_exec.property_moved=The property 'errorCodes' has moved down onto the RuntimeExec class

index.recovery.out_of_date=Indekset er ikke synkroniseret med databasen.
index.tracking.starting=Gendannelse af indeks startet.
index.tracking.complete=Gendannelse af indeks afsluttet.
index.tracking.progress=\ Behandling af transaktioner omkring {0}.
index.recovery.starting=Gendannelse af indeks startet\: {0} transaktioner.
index.recovery.complete=Gendannelse af indeks afsluttet.
index.recovery.progress=\ {0} % fuldf\u00f8rt.
index.recovery.terminated=Gendannelse af indeks afsluttet.

node.archive.msg.busy=En masseoprensning eller gendannelse er i gang

content.http_reader.err.no_connection=Kan ikke forbinde til Alfresco fjernserver via HTTP\: {0}
content.http_reader.err.no_authentication=HTTP-l\u00e6seren kunne ikke godkendes p\u00e5 fjernserveren\: {0}  \n
content.http_reader.err.check_cluster=Kontroller at 'replicateUpdates' og 'replicateUpdatesViaCopy' er aktiveret i mellemlagret 'org.alfresco.cache.ticketsCache'. Kontroller at den generelle klyngekonfiguration er korrekt og fungerende.
content.http_reader.err.unrecognized=Der opstod en ukendt fejl under fors\u00f8g p\u00e5 at hente indhold fra den eksterne server\: \nServer\: {0} \nindhold\: {1} \nhttp-svar\: {2}

metadata.extraction.err.type_conversion=Udtr\u00e6k af metadata mislykkedes, fordi en udtrukket v\u00e6rdi ikke kan konverteres til den kr\u00e6vede type\: \nExtractor\: {0} \nTarget Property QName\: {1} \nRequired Type\: {2} \nExtracted Value\: {3}

transform.err.format_or_password=Kunne ikke konvertere indhold, muligvis p\u00e5 grund af forkert formatering eller passwordbeskyttet fil.

content.routing.err.invalid_default_store=''defaultStoreName'', ''{0}'' refererer ikke til et lager i ''storesByName'' ({1}).
