#X-Generator: crowdin.com
# Content-related messages

content.content_missing=Chyb\u00ed obsah n\u00f3du\: \nn\u00f3d\: {0} \nreader\: {1}  \nObra\u0165te se pros\u00edm na spr\u00e1vce syst\u00e9mu.
content.runtime_exec.property_moved=Vlastnost 'errorCodes' se p\u0159esunula n\u00ed\u017ee na t\u0159\u00eddu RuntimeExec

index.recovery.out_of_date=Indexy nejsou synchronizov\u00e1ny s datab\u00e1z\u00ed.
index.tracking.starting=Obnova index\u016f za\u010dala.
index.tracking.complete=Obnova index\u016f skon\u010dila.
index.tracking.progress=\ Zpracov\u00e1n\u00ed transakc\u00ed kolem {0}.
index.recovery.starting=Obnova index\u016f za\u010dala\: {0} transakc\u00ed.
index.recovery.complete=Obnova index\u016f skon\u010dila.
index.recovery.progress=\ {0} % dokon\u010deno.
index.recovery.terminated=Obnova index\u016f p\u0159eru\u0161ena.

node.archive.msg.busy=Hromadn\u00e9 vymaz\u00e1n\u00ed nebo obnoven\u00ed pr\u00e1v\u011b prob\u00edh\u00e1

content.http_reader.err.no_connection=Nelze se p\u0159ipojit ke vzd\u00e1len\u00e9mu serveru Alfresco p\u0159es HTTP protokol\: {0}
content.http_reader.err.no_authentication=\u010ctec\u00edmu za\u0159\u00edzen\u00ed protokolu HTTP se nezda\u0159ilo ov\u011b\u0159en\u00ed na vzd\u00e1len\u00e9m serveru\: {0}  \n
content.http_reader.err.check_cluster=Ujist\u011bte se, \u017ee volby "replicateUpdates" a "replicateUpdatesViaCopy" jsou povoleny pro cache 'org.alfresco.cache.ticketsCache'.  Zkontrolujte, zda hlavn\u00ed konfigurace clusteru je spr\u00e1vn\u00e1 a funk\u010dn\u00ed.
content.http_reader.err.unrecognized=Do\u0161lo k nezn\u00e1m\u00e9 chyb\u011b p\u0159i pokusu o sta\u017een\u00ed obsahu ze vzd\u00e1len\u00e9ho serveru\:\nServer\: {0}\nObsah\: {1}\nHTTP odpov\u011bdi\: {2}

metadata.extraction.err.type_conversion=Extrakce metadat se nezda\u0159ila, proto\u017ee extrahovanou hodnotu se nepoda\u0159ilo p\u0159ev\u00e9st na po\u017eadovan\u00fd typ.\:\nExtractor\: {0}\nQName c\u00edlov\u00e1 vlastnost\: {1}\nPo\u017eadovan\u00fd typ\: {2}\nExtrahov\u00e1no hodnota\: {3}

transform.err.format_or_password=Nepoda\u0159ilo se p\u0159ev\u00e9st obsah, z\u0159ejm\u011b v d\u016fsledku nespr\u00e1vn\u011b form\u00e1tovan\u00e9ho souboru nebo je soubor chr\u00e1n\u011bn\u00fd heslem.

content.routing.err.invalid_default_store=''defaultStoreName'', ''{0}'' neodkazuje na \u00falo\u017ei\u0161t\u011b v ''storesByName'' ({1}).
